"""Core ports (interfaces) for the GOD MODE AI platform.

Phase 2. These Protocols define the contracts the Core Framework exposes. Concrete
implementations (in-memory now, Redis/Postgres/Qdrant later) are swapped behind them via
the DI container — Hexagonal Architecture: the domain depends on these ports, never on adapters.
"""
from __future__ import annotations

from typing import Any, Awaitable, Callable, Protocol, runtime_checkable

# ---------------------------------------------------------------------------
# Observability
# ---------------------------------------------------------------------------


@runtime_checkable
class ILogger(Protocol):
    def bind(self, **kwargs: Any) -> "ILogger": ...
    def info(self, event: str, **kw: Any) -> None: ...
    def warning(self, event: str, **kw: Any) -> None: ...
    def error(self, event: str, **kw: Any) -> None: ...
    def debug(self, event: str, **kw: Any) -> None: ...


@runtime_checkable
class IMetrics(Protocol):
    def counter(self, name: str, value: float = 1.0, **labels: str) -> None: ...
    def gauge(self, name: str, value: float, **labels: str) -> None: ...
    def observe(self, name: str, value: float, **labels: str) -> None: ...
    def timer(self, name: str, **labels: str) -> "ITimer": ...
    def render(self) -> str: ...


@runtime_checkable
class ITimer(Protocol):
    def __enter__(self) -> "ITimer": ...
    def __exit__(self, *exc: Any) -> None: ...


@runtime_checkable
class IHealthService(Protocol):
    def register(self, name: str, check: Callable[[], Awaitable[dict]]) -> None: ...
    async def report(self) -> tuple[int, dict]: ...


# ---------------------------------------------------------------------------
# Messaging
# ---------------------------------------------------------------------------

Handler = Callable[[dict], Awaitable[None]]


@runtime_checkable
class IEventBus(Protocol):
    async def publish(self, topic: str, payload: dict) -> None: ...
    async def subscribe(self, topic: str, group: str, handler: Handler) -> None: ...
    async def unsubscribe(self, topic: str, group: str) -> None: ...


@runtime_checkable
class IMessageBus(Protocol):
    async def request(self, target: str, payload: dict, timeout: float = 30.0) -> dict: ...
    def handle(self, target: str, handler: Callable[[dict], Awaitable[dict]]) -> None: ...


# ---------------------------------------------------------------------------
# Security
# ---------------------------------------------------------------------------


@runtime_checkable
class IPermissionManager(Protocol):
    async def check(self, principal: str, scope: str) -> bool: ...
    async def require(self, principal: str, scope: str) -> None: ...
    def grant(self, role: str, scope: str) -> None: ...
    def assign(self, principal: str, role: str) -> None: ...


# ---------------------------------------------------------------------------
# Tools & Memory
# ---------------------------------------------------------------------------


@runtime_checkable
class ITool(Protocol):
    name: str
    kind: str
    async def invoke(self, args: dict) -> Any: ...
    def schema(self) -> dict: ...


@runtime_checkable
class IToolRegistry(Protocol):
    def register(self, tool: ITool) -> None: ...
    def get(self, name: str) -> ITool: ...
    def list(self) -> list[str]: ...
    async def invoke(self, name: str, args: dict, *, agent_id: str) -> Any: ...


@runtime_checkable
class IMemoryManager(Protocol):
    async def remember(self, content: str, *, scope: str, owner: str,
                       kind: str = "note", metadata: dict | None = None) -> str: ...
    async def recall(self, query: str, *, scope: str, owner: str, k: int = 8) -> list[dict]: ...
    async def forget(self, memory_id: str) -> None: ...
