"""Soldier catalogue (generated for the AGNI hierarchy). One SoldierSpec per soldier."""
from __future__ import annotations

from dataclasses import dataclass

from backend.soldiers.common import LlmSoldier, MemorySoldier
from backend.soldiers.super_soldier import MediaSoldier, MoviePlannerSoldier, ResearchSoldier


@dataclass
class SoldierSpec:
    name: str
    group: str
    tool: str | None = None
    cls: type | None = None


SOLDIER_CATALOG: list[SoldierSpec] = [
    SoldierSpec("internet", "knowledge", cls=LlmSoldier),
    SoldierSpec("search", "knowledge", cls=LlmSoldier),
    SoldierSpec("research", "knowledge", cls=ResearchSoldier),
    SoldierSpec("news", "knowledge", cls=LlmSoldier),
    SoldierSpec("weather", "knowledge"),
    SoldierSpec("maps", "knowledge"),
    SoldierSpec("translation", "knowledge"),
    SoldierSpec("knowledge_graph", "knowledge", cls=LlmSoldier),
    SoldierSpec("calendar", "planning"),
    SoldierSpec("reminder", "planning"),
    SoldierSpec("task_planning", "planning"),
    SoldierSpec("project_planning", "planning"),
    SoldierSpec("route_planning", "planning"),
    SoldierSpec("goal_planning", "planning"),
    SoldierSpec("movie_planner", "planning", cls=MoviePlannerSoldier),
    SoldierSpec("tool", "execution"),
    SoldierSpec("api", "execution"),
    SoldierSpec("terminal", "execution"),
    SoldierSpec("workflow", "execution"),
    SoldierSpec("automation", "execution"),
    SoldierSpec("long_term_memory", "memory", cls=MemorySoldier),
    SoldierSpec("short_term_memory", "memory"),
    SoldierSpec("semantic_memory", "memory"),
    SoldierSpec("context", "memory"),
    SoldierSpec("file", "memory"),
    SoldierSpec("ocr", "memory"),
    SoldierSpec("pdf", "memory"),
    SoldierSpec("vector_memory", "memory"),
    SoldierSpec("coding", "coding"),
    SoldierSpec("debugging", "coding"),
    SoldierSpec("git", "coding"),
    SoldierSpec("docker", "coding"),
    SoldierSpec("testing", "coding"),
    SoldierSpec("deployment", "coding"),
    SoldierSpec("image", "media"),
    SoldierSpec("video", "media", cls=MediaSoldier),
    SoldierSpec("audio", "media", cls=MediaSoldier),
    SoldierSpec("music", "media", cls=MediaSoldier),
    SoldierSpec("speech", "media"),
    SoldierSpec("vision", "media"),
    SoldierSpec("camera", "media"),
    SoldierSpec("editing", "media"),
    SoldierSpec("banking", "finance"),
    SoldierSpec("loan", "finance"),
    SoldierSpec("credit_card", "finance"),
    SoldierSpec("investment", "finance"),
    SoldierSpec("stock", "finance"),
    SoldierSpec("crypto", "finance"),
    SoldierSpec("shopping", "finance"),
    SoldierSpec("budget", "finance"),
    SoldierSpec("email", "communication"),
    SoldierSpec("whatsapp", "communication"),
    SoldierSpec("sms", "communication"),
    SoldierSpec("call", "communication"),
    SoldierSpec("notification", "communication"),
    SoldierSpec("contacts", "communication"),
    SoldierSpec("social_media", "communication"),
    SoldierSpec("aws", "system"),
    SoldierSpec("azure", "system"),
    SoldierSpec("gcp", "system"),
    SoldierSpec("database", "system"),
    SoldierSpec("kubernetes", "system"),
    SoldierSpec("authentication", "system"),
    SoldierSpec("monitoring", "system"),
    SoldierSpec("logging", "system"),
    SoldierSpec("devops", "system"),
    SoldierSpec("trigger", "automation"),
    SoldierSpec("scheduler", "automation"),
    SoldierSpec("auto_workflow", "automation"),
    SoldierSpec("api_automation", "automation"),
    SoldierSpec("notification_automation", "automation"),
    SoldierSpec("device_control", "device"),
    SoldierSpec("app_management", "device", cls=LlmSoldier),
    SoldierSpec("settings", "device"),
    SoldierSpec("flashlight", "device"),
    SoldierSpec("volume", "device"),
    SoldierSpec("brightness", "device"),
    SoldierSpec("battery", "device"),
    SoldierSpec("storage", "device"),
    SoldierSpec("file_manager", "device"),
    SoldierSpec("clipboard", "device"),
    SoldierSpec("dev_camera", "device"),
    SoldierSpec("gallery", "device"),
    SoldierSpec("phone", "device"),
    SoldierSpec("dev_contacts", "device"),
    SoldierSpec("bluetooth", "device"),
    SoldierSpec("wifi", "device"),
    SoldierSpec("nfc", "device"),
    SoldierSpec("sensor", "device"),
    SoldierSpec("accessibility", "device"),
    SoldierSpec("device_health", "device"),
    SoldierSpec("malware", "security"),
    SoldierSpec("antivirus", "security"),
    SoldierSpec("threat_detection", "security"),
    SoldierSpec("phishing", "security"),
    SoldierSpec("scam_detection", "security"),
    SoldierSpec("network_security", "security"),
    SoldierSpec("firewall", "security"),
    SoldierSpec("encryption", "security"),
    SoldierSpec("password", "security"),
    SoldierSpec("privacy", "security"),
    SoldierSpec("secure_vault", "security"),
    SoldierSpec("identity_protection", "security"),
    SoldierSpec("incident_response", "security"),
    SoldierSpec("smart_home", "iot"),
    SoldierSpec("smart_lighting", "iot"),
    SoldierSpec("smart_camera", "iot"),
    SoldierSpec("smart_tv", "iot"),
    SoldierSpec("smart_speaker", "iot"),
    SoldierSpec("appliance", "iot"),
    SoldierSpec("vehicle", "iot"),
    SoldierSpec("wearable", "iot"),
    SoldierSpec("medical_iot", "iot"),
    SoldierSpec("industrial_iot", "iot"),
    SoldierSpec("energy_management", "iot"),
    SoldierSpec("matter_protocol", "iot"),
    SoldierSpec("intelligence", "asi"),
    SoldierSpec("reasoning", "asi"),
    SoldierSpec("planning_optimization", "asi"),
    SoldierSpec("performance", "asi"),
    SoldierSpec("memory_optimization", "asi"),
    SoldierSpec("cpu_optimization", "asi"),
    SoldierSpec("gpu_optimization", "asi"),
    SoldierSpec("battery_optimization", "asi"),
    SoldierSpec("storage_optimization", "asi"),
    SoldierSpec("cache_optimization", "asi"),
    SoldierSpec("thermal_management", "asi"),
    SoldierSpec("prediction", "asi"),
    SoldierSpec("learning", "asi"),
    SoldierSpec("decision", "asi"),
    SoldierSpec("knowledge_evolution", "asi"),
    SoldierSpec("ai_model_selection", "asi"),
    SoldierSpec("resource_allocation", "asi"),
    SoldierSpec("self_diagnostics", "asi"),
    SoldierSpec("wake_word", "voice"),
    SoldierSpec("speech_recognition", "voice"),
    SoldierSpec("speaker_recognition", "voice"),
    SoldierSpec("voice_biometrics", "voice"),
    SoldierSpec("text_to_speech", "voice"),
    SoldierSpec("noise_cancellation", "voice"),
    SoldierSpec("emotion_detection", "voice"),
    SoldierSpec("language_understanding", "voice"),
    SoldierSpec("accent_adaptation", "voice"),
    SoldierSpec("offline_voice", "voice"),
    SoldierSpec("call_assistant", "voice"),
    SoldierSpec("conversation", "voice"),
]
